basic.forever(function () {
    basic.showString("PROYECTO 5")
    basic.showString("DESAFIO DE UNA BRUJULA ")
    basic.showString("NORTE")
    basic.showArrow(ArrowNames.North)
    basic.showString("NORESTE")
    basic.showArrow(ArrowNames.NorthEast)
    basic.showString("NOROSTE")
    basic.showArrow(ArrowNames.NorthWest)
    basic.showString("OESTE")
    basic.showArrow(ArrowNames.West)
    basic.showString("ESTE")
    basic.showArrow(ArrowNames.East)
    basic.showString("SURESTE")
    basic.showArrow(ArrowNames.SouthEast)
    basic.showString("SUROESTE")
    basic.showArrow(ArrowNames.SouthWest)
    basic.showString("SUR")
    basic.showArrow(ArrowNames.South)
})
